package com.ivdr.domain.audit.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.UUID;

/**
 * JPA entity representing a single, immutable row in the {@code audit_logs} table.
 *
 * <p>Audit logs are <em>append-only</em>: once a row is written it is never updated
 * or deleted (barring administrator-level data-retention purges that occur outside
 * normal application flow). The {@link #prePersist()} lifecycle hook enforces this
 * by setting {@code createdAt} automatically; no {@code @PreUpdate} hook exists.
 *
 * <p>The {@code metadata} column stores arbitrary JSON context (document names,
 * workspace IDs, error codes, etc.) using Hibernate's native JSON type mapping.
 *
 * <p>The {@code eventId} column carries a unique constraint that the consumer layer
 * uses for idempotent processing: if an event has already been persisted (e.g. after
 * a Kafka redelivery) the consumer simply skips it.
 */
@Entity
@Table(
        name = "audit_logs",
        indexes = {
                @Index(name = "idx_audit_org_created",   columnList = "organization_id, created_at DESC"),
                @Index(name = "idx_audit_user_created",  columnList = "user_id, created_at DESC"),
                @Index(name = "idx_audit_event_type",    columnList = "event_type"),
                @Index(name = "idx_audit_is_anomaly",    columnList = "is_anomaly")
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AuditLog {

    // -------------------------------------------------------------------------
    // Identity
    // -------------------------------------------------------------------------

    /**
     * Surrogate primary key – generated by the database (UUID strategy).
     * The application never sets this field directly.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * The unique identifier carried inside the {@link com.ivdr.domain.audit.event.AuditEvent}
     * Kafka message. Used as an idempotency key: the consumer rejects duplicate deliveries
     * by checking {@code existsByEventId} before persisting.
     */
    @Column(name = "event_id", unique = true, nullable = false, updatable = false)
    private UUID eventId;

    // -------------------------------------------------------------------------
    // Tenant / actor context
    // -------------------------------------------------------------------------

    /** The organisation (tenant) this event belongs to. */
    @Column(name = "organization_id", nullable = false, updatable = false)
    private UUID organizationId;

    /**
     * The user who triggered the action. May be {@code null} for system-generated
     * events (scheduled jobs, background services, etc.).
     */
    @Column(name = "user_id", updatable = false)
    private UUID userId;

    // -------------------------------------------------------------------------
    // Event classification
    // -------------------------------------------------------------------------

    /**
     * String representation of {@link com.ivdr.domain.audit.event.AuditEventType}.
     * Stored as a plain VARCHAR so that the column remains queryable even if the
     * enum is later extended.
     */
    @Column(name = "event_type", nullable = false, updatable = false, length = 64)
    private String eventType;

    // -------------------------------------------------------------------------
    // Affected resource
    // -------------------------------------------------------------------------

    /**
     * Logical category of the resource (e.g. {@code "document"}, {@code "workspace"},
     * {@code "user"}).
     */
    @Column(name = "resource_type", updatable = false, length = 64)
    private String resourceType;

    /** Opaque identifier of the specific resource instance. */
    @Column(name = "resource_id", updatable = false, length = 255)
    private String resourceId;

    // -------------------------------------------------------------------------
    // Network context
    // -------------------------------------------------------------------------

    /** Source IPv4/IPv6 address of the HTTP request, if available. */
    @JdbcTypeCode(SqlTypes.OTHER)
    @Column(name = "ip_address", updatable = false, columnDefinition = "inet")
    private String ipAddress;

    /** HTTP {@code User-Agent} header value, if available. */
    @Column(name = "user_agent", updatable = false, length = 512)
    private String userAgent;

    // -------------------------------------------------------------------------
    // Payload
    // -------------------------------------------------------------------------

    /**
     * Arbitrary JSON metadata context. Stored using Hibernate's native JSON
     * column type; automatically serialised/deserialised by the driver.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "metadata", columnDefinition = "jsonb", updatable = false)
    private Map<String, Object> metadata;

    /**
     * HMAC-SHA-256 signature over the canonical event payload.
     * Used by the consumer to verify event integrity before persisting.
     */
    @Column(name = "signature", updatable = false, length = 128)
    private String signature;

    // -------------------------------------------------------------------------
    // Anomaly flag
    // -------------------------------------------------------------------------

    /**
     * Set to {@code true} by {@link com.ivdr.domain.audit.service.AnomalyDetectionService}
     * when the event (or a cluster of related events) is deemed anomalous.
     * The field intentionally allows post-hoc updates by the anomaly service
     * (the only mutable field in this entity).
     */
    @Column(name = "is_anomaly", nullable = false)
    @Builder.Default
    private boolean isAnomaly = false;

    // -------------------------------------------------------------------------
    // Timestamps
    // -------------------------------------------------------------------------

    /**
     * Wall-clock time at which this row was persisted.
     * Set automatically by {@link #prePersist()} and never updated.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    // -------------------------------------------------------------------------
    // Lifecycle hooks
    // -------------------------------------------------------------------------

    /**
     * Sets {@link #createdAt} to the current date-time before the entity is
     * first written to the database. No {@code @PreUpdate} hook is defined
     * because audit rows are append-only.
     */
    @PrePersist
    protected void prePersist() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}
