package com.ivdr.domain.document.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity that maps to the {@code documents} table.
 *
 * <p>Design notes:
 * <ul>
 *   <li>UUID primary key is generated by the database (PostgreSQL {@code gen_random_uuid()})
 *       so we rely on {@link GenerationType#UUID} — available since Hibernate 6 / Spring Boot 3.</li>
 *   <li>The {@code tags} column uses the native PostgreSQL {@code text[]} type.
 *       Hibernate 6 maps Java {@code String[]} to it transparently via
 *       {@link JdbcTypeCode} with {@link SqlTypes#ARRAY}.</li>
 *   <li>Soft-delete is implemented via the {@code status} field; a value of
 *       {@code "DELETED"} marks the record as logically removed.</li>
 *   <li>{@link #prePersist()} and {@link #preUpdate()} maintain the audit timestamps
 *       automatically so callers do not have to set them manually.</li>
 * </ul>
 */
@Entity
@Table(
        name = "documents",
        indexes = {
                @Index(name = "idx_documents_workspace_id",  columnList = "workspace_id"),
                @Index(name = "idx_documents_organization_id", columnList = "organization_id"),
                @Index(name = "idx_documents_status",        columnList = "status"),
                @Index(name = "idx_documents_uploaded_by",   columnList = "uploaded_by")
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Document {

    // -------------------------------------------------------------------------
    // Primary key
    // -------------------------------------------------------------------------

    /**
     * Surrogate primary key — UUID generated by the database so it is
     * available immediately after {@code INSERT} without a separate round-trip.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // -------------------------------------------------------------------------
    // Ownership / tenancy
    // -------------------------------------------------------------------------

    /**
     * Foreign key to the workspace this document belongs to.
     * Used as the primary partition key for multi-tenant queries.
     */
    @Column(name = "workspace_id", nullable = false, updatable = false)
    private UUID workspaceId;

    /**
     * Foreign key to the organisation — stored denormalised here so that
     * Row-Level Security (RLS) policies can enforce tenancy without a join.
     */
    @Column(name = "organization_id", nullable = false, updatable = false)
    private UUID organizationId;

    // -------------------------------------------------------------------------
    // Document metadata
    // -------------------------------------------------------------------------

    /** Human-readable document name (e.g. original filename). */
    @Column(name = "name", nullable = false, length = 512)
    private String name;

    /** Optional free-text description provided by the uploader. */
    @Column(name = "description", columnDefinition = "text")
    private String description;

    // -------------------------------------------------------------------------
    // Storage
    // -------------------------------------------------------------------------

    /**
     * S3 object key used to locate the file in the configured bucket.
     * Format: {@code {orgId}/{workspaceId}/{UUID}-{filename}}.
     */
    @Column(name = "file_key", nullable = false, unique = true, length = 1024)
    private String fileKey;

    /** Raw size of the stored file in bytes. */
    @Column(name = "file_size_bytes", nullable = false)
    private long fileSizeBytes;

    /** MIME type of the stored file (e.g. {@code application/pdf}). */
    @Column(name = "content_type", nullable = false, length = 255)
    private String contentType;

    // -------------------------------------------------------------------------
    // Versioning and lifecycle
    // -------------------------------------------------------------------------

    /**
     * Optimistic versioning counter for document revisions.
     * Starts at 1 on first upload; incremented on each update.
     */
    @Column(name = "version", nullable = false)
    @Builder.Default
    private int version = 1;

    /**
     * Lifecycle status of the document.
     * Valid values: {@code PROCESSING}, {@code ACTIVE}, {@code ARCHIVED}, {@code DELETED}.
     */
    @Column(name = "status", nullable = false, length = 32)
    @Builder.Default
    private String status = "PROCESSING";

    // -------------------------------------------------------------------------
    // Tagging and AI features
    // -------------------------------------------------------------------------

    /**
     * Free-form tags stored as a PostgreSQL native {@code text[]} array.
     * Queried via GIN index for efficient containment searches.
     */
    @Column(name = "tags", columnDefinition = "text[]")
    @JdbcTypeCode(SqlTypes.ARRAY)
    private String[] tags;

    /**
     * AI-generated summary produced asynchronously after upload.
     * Nullable until the async summarisation job completes.
     */
    @Column(name = "ai_summary", columnDefinition = "text")
    private String aiSummary;

    // -------------------------------------------------------------------------
    // Integrity
    // -------------------------------------------------------------------------

    /**
     * SHA-256 hex-encoded checksum of the file content computed at upload time.
     * Used for deduplication and integrity verification.
     */
    @Column(name = "checksum_sha256", nullable = false, length = 64)
    private String checksumSha256;

    // -------------------------------------------------------------------------
    // Audit fields
    // -------------------------------------------------------------------------

    /** UUID of the user who uploaded this document. */
    @Column(name = "uploaded_by", nullable = false, updatable = false)
    private UUID uploadedBy;

    /** Timestamp set automatically when the entity is first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp updated automatically whenever the entity is modified. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    // -------------------------------------------------------------------------
    // JPA lifecycle hooks
    // -------------------------------------------------------------------------

    /**
     * Sets {@link #createdAt} and {@link #updatedAt} before the first
     * {@code INSERT}. Both fields are assigned the same instant so the record
     * is self-consistent from the moment it is written.
     */
    @PrePersist
    protected void prePersist() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Refreshes {@link #updatedAt} before every subsequent {@code UPDATE}
     * so that consumers can always determine when the document was last
     * modified.
     */
    @PreUpdate
    protected void preUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
